"""Add quiz_completed column to users table

Revision ID: 251f5e95c4b1
Revises: 54afa6c40496
Create Date: 2025-02-11 16:22:17.262050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251f5e95c4b1'
down_revision = '54afa6c40496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('clicked_whatsapp')
        batch_op.drop_column('course_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_completed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('clicked_whatsapp', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('quiz_completed')

    # ### end Alembic commands ###
